/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 04 22:02:11 GMT 2025
 */

package evo.services;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import services.LanguageService;
import services.LanguageService_ESTest_scaffolding;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false, useJEE = true)
public class LanguageService_ESTest extends LanguageService_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LanguageService.setLanguage("en", "HQ");
      String string0 = LanguageService.getCurrentCountry();
      assertEquals("HQ", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String string0 = LanguageService.getCurrentLanguage();
      assertEquals("en", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LanguageService.setLanguage("", "");
      String string0 = LanguageService.getCurrentLanguage();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      String string0 = LanguageService.getValue("");
      assertEquals("Key '' not found in language: en", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      LanguageService languageService0 = new LanguageService();
      assertEquals("", languageService0.getCurrentCountry());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      String string0 = LanguageService.getCurrentCountry();
      assertEquals("", string0);
  }
}
