/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 04 22:39:48 GMT 2025
 */

package evo.services;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import services.TestDataGenerator;
import services.TestDataGenerator_ESTest_scaffolding;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false, useJEE = true)
public class TestDataGenerator_ESTest extends TestDataGenerator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TestDataGenerator testDataGenerator0 = new TestDataGenerator();
      int int0 = (-550);
      testDataGenerator0.generateRandomUser((-2503));
      testDataGenerator0.generateRandomUsers((-550));
      testDataGenerator0.generateRandomUsers((-550));
      testDataGenerator0.generateRandomUsers((-550));
      testDataGenerator0.generateRandomUser(0);
      testDataGenerator0.generateRandomUser((-550));
      testDataGenerator0.generateRandomUser((-2503));
      testDataGenerator0.generateRandomUsers(0);
      testDataGenerator0.generateRandomUsers((-2503));
      testDataGenerator0.generateRandomUser((-550));
      testDataGenerator0.generateRandomUser((-1735));
      testDataGenerator0.generateRandomUsers(5);
      int int1 = 1293;
      // Undeclared exception!
      testDataGenerator0.generateRandomUsers(1293);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TestDataGenerator testDataGenerator0 = new TestDataGenerator();
      testDataGenerator0.generateRandomUser(1);
      testDataGenerator0.generateRandomUser(2358);
      // Undeclared exception!
      testDataGenerator0.generateRandomUsers(1063);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TestDataGenerator testDataGenerator0 = new TestDataGenerator();
      testDataGenerator0.generateRandomUsers(6);
      testDataGenerator0.generateRandomUser(380);
      testDataGenerator0.generateRandomUser(380);
      testDataGenerator0.generateRandomUser(380);
      testDataGenerator0.generateRandomUser(380);
      testDataGenerator0.generateRandomUsers((-2333));
      testDataGenerator0.generateRandomUser((-2333));
      testDataGenerator0.generateRandomUser((-868));
      testDataGenerator0.generateRandomUsers(380);
      testDataGenerator0.generateRandomUser((-2333));
      testDataGenerator0.generateRandomUsers((-2333));
      testDataGenerator0.generateRandomUser(125);
      testDataGenerator0.generateRandomUsers((-2333));
      testDataGenerator0.generateRandomUser((-2333));
      testDataGenerator0.generateRandomUser(380);
      testDataGenerator0.generateRandomUser(0);
      testDataGenerator0.generateRandomUsers(0);
      testDataGenerator0.generateRandomUsers(0);
      testDataGenerator0.generateRandomUsers(0);
      testDataGenerator0.generateRandomUsers(0);
      testDataGenerator0.generateRandomUser(2);
      testDataGenerator0.generateRandomUser((-2333));
      // Undeclared exception!
      testDataGenerator0.generateRandomUsers(125);
  }
}
